flowchart TD

A([开始])

A --> B[创建多项式 A]
B --> C[输入项数 n]
C --> D[循环输入系数和指数]
D --> E[按指数降序插入]
E --> F[合并同类项并删除零系数项]
F --> G{还有未输入项?}

G -- 是 --> D
G -- 否 --> H[得到多项式 A]

H --> I[创建多项式 B]
%%I --> J[重复建立过程]
%%J --> K[得到多项式 B]

I --> L[输出 A 和 B]

L --> M[进行多项式加减运算<br>输出运算结果]
%%M --> N[输出运算结果]

M --> O[释放链表空间]

O --> P([结束])