flowchart TD

    A([开始])

    B[/输入 n, m/]

    C["初始化 st数组为0<br/>初始化 a[i]=i+1"]

    D["调用 josephus_circle()"]

    E{n==1?}

    F["返回 a[0]"]

    G[初始化<br/>num=n<br/>cnt=0<br/>index=0]

    H{num≠1?}

    I{"st[index]==1?"}

    J["index=(index+1)%n"]

    K[cnt++]

    L{cnt==m?}

    M["st[index]=1<br/>cnt=0<br/>num--"]

    N["index=(index+1)%n"]

    O[i=0]

    P{i<n?}

    Q{"st[i]==0?"}

    R["返回 a[i]"]

    S[i++]

    T[返回 -1]

    U[输出结果 ret]

    V([结束])

    A --> B
    B --> C
    C --> D
    D --> E

    E -- 是 --> F
    F --> U

    E -- 否 --> G
    G --> H

    H -- 是 --> I

    I -- 是 --> J
    J --> H

    I -- 否 --> K
    K --> L

    L -- 是 --> M
    M --> N

    L -- 否 --> N

    N --> H

    H -- 否 --> O

    O --> P

    P -- 是 --> Q

    Q -- 是 --> R
    R --> U

    Q -- 否 --> S
    S --> P

    P -- 否 --> T
    T --> U

    U --> V