flowchart TD
    Start([开始]) --> Create[create: 输入数据]
    Create --> Insert[insert: 插入节点]
    
    Insert --> Cond1{coef == 0?}
    Cond1 -- 否 --> Cond2{指数相同?}
    
    Cond2 -- 是 --> Add[系数相加]
    Add --> Cond3{相加后系数 == 0?}
    Cond3 -- 是 --> Delete[删除节点]
    
    Cond2 -- 否 --> Link[按降序链接新节点]
    
    Cond1 -- 是 --> Print[printPoly: 打印多项式]
    Delete --> Print
    Cond3 -- 否 --> Print
    Link --> Print
    
    Print --> AddFunc[add: 两个多项式相加]
    AddFunc --> SubFunc[subtract: 两个多项式相减]
    SubFunc --> Destroy[destroy: 释放内存]
    Destroy --> End([结束])